// Task.js - Mongoose schema for a to-do task
const mongoose = require("mongoose");

const taskSchema = new mongoose.Schema(
  {
    user: {
      // Links this task to the user who owns it
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    title: {
      type: String,
      required: [true, "Task title is required"],
      trim: true,
    },
    subject: {
      type: String,
      trim: true,
      default: "General",
    },
    description: {
      type: String,
      trim: true,
      default: "",
    },
    dueDate: {
      type: Date,
      required: [true, "Due date is required"],
    },
    weight: {
      // Importance of the task, 1 (low) - 10 (high)
      type: Number,
      min: 1,
      max: 10,
      default: 5,
    },
    completionPercent: {
      // How much of the task is done, 0-100
      type: Number,
      min: 0,
      max: 100,
      default: 0,
    },
    status: {
      type: String,
      enum: ["pending", "in-progress", "completed"],
      default: "pending",
    },
    // Subtasks generated by Gemini AI (or added manually)
    subtasks: [
      {
        title: { type: String, required: true },
        deadline: { type: Date },
        done: { type: Boolean, default: false },
      },
    ],
  },
  { timestamps: true }
);

module.exports = mongoose.model("Task", taskSchema);
